### ISSUE TITLE
Datasource not found when using provisioning

### ISSUE THREAD

**Issue by marcbichon** [doitintl/bigquery-grafana#201]
## Expected Behavior
The datasource is correctly created using the provisioning file and the dashboard is displayed correctly.

## Actual Behavior
The error message "Datasource named test was not found" is displayed on the dashboard page.

## Steps to Reproduce the Problem

  1. Follow the steps described [here](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource) to use a BigQuery DataSource with GCE Default Service Account.
  2. Provision the datasource using the following file:
```
apiVersion: 1

datasources:
- name: test
  type: doitintl-bigquery-datasource
  access: proxy
  jsonData:
     authenticationType: gce
```
  3. Try to display the dashboard.

## Specifications

  - Version: 1.0.5
  - Grafana Version: 5.4.3
