### ISSUE TITLE
Not able to set Processing Location in ConfigMap

### ISSUE THREAD

**Issue by mihail-sky** [doitintl/bigquery-grafana#211]
## Bug Report
I'm configuring the _Processing Location_ variable to _EU_ with the following ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-bigquery-jwt
  namespace: monitoring
  labels:
    manually_added: "true"
    grafana_datasource: "1"
data:
  bigquery-datasource-jwt.yaml: |-
    apiVersion: 1
    datasources:
    - name: Google BigQuery JWT
      type: doitintl-bigquery-datasource
      access: proxy
      jsonData:
        authenticationType: jwt
        clientEmail: [..]
        defaultProject: [..]
        tokenUri: https://oauth2.googleapis.com/token
        processingLocations: EU
        sendUsageData: false
      secureJsonData:
          privateKey: |
            -----BEGIN PRIVATE KEY-----
            [..]
            -----END PRIVATE KEY-----
      version: 2
      readOnly: false
```
## Expected Behavior
When I go to Grafana Configuration -> Data Sources -> Google BigQuery JWT I expect to see Processing Location set to European Union (EU). 

## Actual Behavior
Processing Location has selected an empty value. 

## Specifications

  - Version: 1.0.6
  - Platform: Kubernetes
  - Grafana Version: Grafana v6.3.5 (commit: 67bad72)
