### ISSUE TITLE
Unable to use plugin with GKE Workload Identity

### ISSUE THREAD

**Issue by medzin** [doitintl/bigquery-grafana#233]
## Bug Report

I'm unable to use the plugin with [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). I get following error:

> required: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

Data source configuration:

```yaml
- name: xxx
  type: doitintl-bigquery-datasource
  access: proxy
  jsonData:
    authenticationType: gce
    defaultProject: xxx
```

## Steps to Reproduce the Problem

  1. Deploy [Grafana Helm chart](https://github.com/helm/charts/tree/master/stable/grafana) on GKE cluster
  1. Configure Workload Identity for the grafana service account
  1. Add BigQuery data source and test it

## Specifications

  - Version: 1.0.7
  - Platform: Docker/GKE
  - Grafana Version: v6.7.1
