### ISSUE TITLE
Problem with alerting

### ISSUE THREAD

**Issue by tomashman8** [doitintl/bigquery-grafana#265]
## Bug Report
When creating an Alert instead of it working correctly and alerting we get this:

Execution Error: tsdb.HandleRequest() error Could not find executor for data source type: doitintl-bigquery-datasource

I have already made sure doitintl-bigquery-datasource is listed as an unsigned plugin.

## Expected Behavior
Alerts being able to be sent.

## Actual Behavior
I get this error message:

Execution Error: tsdb.HandleRequest() error Could not find executor for data source type: doitintl-bigquery-datasource

## Steps to Reproduce the Problem

  1. Create a dashboard with graph and use plugin datasource doitintl-bigquery-datasource.
  2. Setup an alert based upon that graph.

## Specifications

  - Version: 2.0.0
  - Platform: Kubernetes/Prometheus Operator
  - Grafana Version: 7.0.3

**Comment by tomer-harpaz** [comment]
I get the same error
Version:2.0.0
Platform: GKE
Grafana Version: Grafana v7.0.3

**Comment by LiorRacer** [comment]
Hi all,
It will be very helpful if one of you can share the deployment yaml file, so I can work with the enviroment

**Comment by sergiojoker11** [comment]
@LiorRacer I am replying on behalf of @tomashman8 (we work for the same organization).
Here is the relevant helm values where we configure the plugin.
```
grafana:
  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: "doitintl-bigquery-datasource"
  adminPassword: XXXXXXXXXXXXXXXXXXXX
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.monitoring.flexys.co.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.monitoring.flexys.co.uk
  plugins:
    - https://github.com/doitintl/bigquery-grafana/archive/2.0.0.zip;doit-bigquery-datasource
  notifiers:
    notifiers.yaml:
      notifiers:
        - name: Stage-Alerts
          type: slack
          uid: Grafana-Stage
          # either
          org_id: 1
          is_default: false
          send_reminder: true
          frequency: 1h
          disable_resolve_message: false
          # See `Supported Settings` section for settings supporter for each
          # alert notification type.
          settings:
            recipient: '#stage-alerts'
            token: 'xoxb'
            uploadImage: true
            url: <Some_URL_TO_Slack>
  sidecar:
    datasources:
      enabled: true
```
