### ISSUE TITLE
When using GKE workload identity setting the defaultProject in the datasource configuration has no effect

### ISSUE THREAD

**Issue by wilhelmi** [doitintl/bigquery-grafana#278]
## Expected Behavior

The ability to set the default project to something other than project running the GKE cluster.

## Actual Behavior

The BigQuery connection is only established within the project hosting the GKE cluster

## Steps to Reproduce the Problem

1. Deploy into a GKE cluster via Workload Identity in project-a
1. Configure the datasource: 
```yaml
apiVersion: 1

datasources:
- name: audit-logs
  type: doitintl-bigquery-datasource
  access: proxy
  isDefault: true
  jsonData:
       authenticationType: gce
       defaultProject: project-b
       processingLocation: US
  version: 2
  readOnly: false
```
  1. When exploring the datasource the only project that can be selected in the query window is project-a

## Specifications

  - Version: latest
  - Platform: GKE
  - Grafana Version: 7.1.5
