### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#393]
## Bug Report

On Chrome on ios - using Safari below the hood - I get the following error when loading the data source on a dashboard or navigating to the Google BigQuery data source in the data sources section of my Grafana setup:

```
Invalid regular expression: invalid group specifier name
Instantiating https://***/public/plugins/doitintl-bigquery-datasource/module.js
Loading plugins/doitintl-bigquery-datasource/module
```

This seems to be related to Safari not supporting lookbehind in regular expressions, see https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

## Expected Behavior

On Chrome on Mac it works as expected. I'm using plugin version `2.0.3` straight from the Grafana plugins section. Using it with Grafana `v8.3.3`.

## Actual Behavior

Returns the error document above and doesn't render any dashboard using the data source.

## Steps to Reproduce the Problem

1. Install Grafana with Helm chart version `6.20.4` and 
```
plugins:
- doitintl-bigquery-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Google BigQuery
      type: doitintl-bigquery-datasource
      access: proxy
      isDefault: true
      jsonData:
        authenticationType: jwt
        clientEmail: ***
        defaultProject: ***
        tokenUri: https://oauth2.googleapis.com/token
        processingLocation: EU
      secureJsonData:
        privateKey: |
          -----BEGIN PRIVATE KEY-----
          ***
          -----END PRIVATE KEY-----
    version: 2
    readOnly: false
```
2. Go to the Grafana instance in the browser and navigate to the Bigquery Datasource

## Specifications

- Version: `2.0.3`
- Platform: docker image `grafana/grafana:8.3.3`
- Grafana Version: `v8.3.3 (30bb7a93ca)`
